name: CI pipeline

on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  run-tests :
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Unity test project
      run: |
        # Clone the official GameCI test project
        git clone --depth=1 https://github.com/game-ci/unity-actions.git temp-unity-actions
        mkdir -p UnityTestProject
        cp -r temp-unity-actions/test-projects/test-project/. UnityTestProject/
        
        # Copy ThunderKit package into the test project's Packages folder
        mkdir -p UnityTestProject/Packages/ThunderKit
        rsync -a ./ThunderKit/ UnityTestProject/Packages/ThunderKit/

    - name: Run tests
      uses: game-ci/unity-test-runner@v4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        testMode: EditMode
        unityVersion: "6000.0.53f1"
        projectPath: "UnityTestProject"

    - name: Report Test Results
      uses: dorny/test-reporter@v2
      if: always()
      with:
        name: Unity Tests
        path: TestResults/*.xml
        reporter: java-junit