name: CI pipeline

on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  run-tests :
    runs-on: ubuntu-latest
    strategy:
      matrix:
        unity-version: [
          "6000.0.53f1",
          "2022.1.24f1",
          "2020.3.48f1",
          "2019.4.40f1",
          "2018.4.36f1"
        ]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Unity test project
      run: |
        # Clone the official GameCI test project
        git clone --depth=1 https://github.com/game-ci/unity-actions.git temp-unity-actions
        mkdir -p UnityTestProject
        cp -r temp-unity-actions/test-projects/test-project/. UnityTestProject/
        rm -rf temp-unity-actions
        
        # Copy ThunderKit package into the test project's Packages folder
        mkdir -p UnityTestProject/Packages/com.passivepicasso.thunderkit
        rsync -a --exclude 'UnityTestProject' ./ UnityTestProject/Packages/com.passivepicasso.thunderkit/

    - name: Run Tests (Unity ${{ matrix.unity-version }})
      uses: game-ci/unity-test-runner@v4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        testMode: EditMode
        unityVersion: ${{ matrix.unity-version }}
        projectPath: "UnityTestProject"

    - name: Report Test Results
      uses: dorny/test-reporter@v2
      if: always()
      with:
        name: Unity ${{ matrix.unity-version }}
        path: artifacts/*.xml
        reporter: nunit

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Unity ${{ matrix.unity-version }}
        path: artifacts
        retention-days: 5